#!/usr/bin/env python3
"""Emit GSDrawScanlineStaticKeys.inc from harvested SW rasterizer selectors.

usage: pcsx2_sw_static_keys.py KEYS_FILE [KEYS_FILE ...] [--existing INC] > GSDrawScanlineStaticKeys.inc

KEYS_FILE is what a bridge session writes with RRV_PCSX2_GS_SW_KEYS=<file>
(lines "ds <hex> <draws> ..." and "sp <hex> <draws> ..."). --existing merges
the keys already in an .inc, so a new harvest only adds selectors. The output
is the table the PCSX2 bridge patch compiles into ahead-of-time specialised
rasterizer functions (pcsx2/GS/Renderers/SW/GSDrawScanlineStaticKeys.inc).
Selector keys are GS register-state bit fields; they carry no game data.
"""
from __future__ import annotations

import argparse
import re
import sys

HEADER = """// RRV bridge: rasterizer selectors specialised ahead of time.
// Generated by scripts/pcsx2_sw_static_keys.py from selector keys harvested
// with RRV_PCSX2_GS_SW_KEYS (GS register-state bit fields only).
// RRV_SW_DS_KEY(k): GSDrawScanline selector; RRV_SW_SP_KEY(k): SetupPrim key.
// Keep each list sorted ascending.
"""


def read_keys(path: str, ds: set[int], sp: set[int]) -> None:
    with open(path, encoding="utf-8") as stream:
        for line in stream:
            parts = line.split()
            if len(parts) >= 2 and parts[0] in ("ds", "sp"):
                (ds if parts[0] == "ds" else sp).add(int(parts[1], 16))


def read_inc(path: str, ds: set[int], sp: set[int]) -> None:
    text = open(path, encoding="utf-8").read()
    for kind, value in re.findall(r"RRV_SW_(DS|SP)_KEY\((0x[0-9A-Fa-f]+)\)", text):
        (ds if kind == "DS" else sp).add(int(value, 16))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("keys", nargs="+")
    parser.add_argument("--existing")
    args = parser.parse_args()
    ds: set[int] = set()
    sp: set[int] = set()
    for path in args.keys:
        read_keys(path, ds, sp)
    if args.existing:
        read_inc(args.existing, ds, sp)
    out = [HEADER]
    out.append(f"// {len(ds)} draw selectors, {len(sp)} setup selectors\n")
    out.extend(f"RRV_SW_DS_KEY(0x{k:016X})\n" for k in sorted(ds))
    out.extend(f"RRV_SW_SP_KEY(0x{k:016X})\n" for k in sorted(sp))
    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
