// rrv_stubs.cpp — AUTO-GENERATED by scripts/generate_stubs.py
// Do not edit by hand; re-run the generator after modifying config/rrv.toml.

#include "ps2_runtime_macros.h"
#include "ps2_runtime.h"
#include "ps2_stubs.h"
#include "ps2_syscalls.h"
#include "Stubs/Common.h"
#include "ps2_recompiled_stubs.h"
#include "Stubs/Unimplemented.h"
#include "rrv_hle.h"

void sub_002C3000_0x02c3000(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceGsResetGraph(rdram, ctx, runtime);
}

void sub_002C3110_0x02c3110(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceGsResetPath(rdram, ctx, runtime);
}

void sub_002C3178_0x02c3178(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceGsSetDefDispEnv(rdram, ctx, runtime);
}

void sub_002C33B8_0x02c33b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceGsPutDispEnv(rdram, ctx, runtime);
}

void sub_002C3458_0x02c3458(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceGsSyncV(rdram, ctx, runtime);
}

void sub_002C34D0_0x02c34d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceGsSyncPath(rdram, ctx, runtime);
}

void sub_002C37E8_0x02c37e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceGsSetDefLoadImage(rdram, ctx, runtime);
}

void sub_002C39D0_0x02c39d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceGsExecLoadImage(rdram, ctx, runtime);
}

void sub_002C3B90_0x02c3b90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::memclr(rdram, ctx, runtime);
}

void sub_002C3BC8_0x02c3bc8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaGetChan(rdram, ctx, runtime);
}

void sub_002C3BF0_0x02c3bf0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaReset(rdram, ctx, runtime);
}

void sub_002C3CE0_0x02c3ce0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaPutEnv(rdram, ctx, runtime);
}

void sub_002C3EB8_0x02c3eb8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaGetEnv(rdram, ctx, runtime);
}

void sub_002C3EF0_0x02c3ef0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaPutStallAddr(rdram, ctx, runtime);
}

void sub_002C3F18_0x02c3f18(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaSend(rdram, ctx, runtime);
}

void sub_002C3FF0_0x02c3ff0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaSendN(rdram, ctx, runtime);
}

void sub_002C40D8_0x02c40d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaSendI(rdram, ctx, runtime);
}

void sub_002C41C0_0x02c41c0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaRecv(rdram, ctx, runtime);
}

void sub_002C4288_0x02c4288(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaRecvN(rdram, ctx, runtime);
}

void sub_002C4378_0x02c4378(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaRecvI(rdram, ctx, runtime);
}

void sub_002C4478_0x02c4478(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaSync(rdram, ctx, runtime);
}

void sub_002C4540_0x02c4540(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDmaWatch(rdram, ctx, runtime);
}

void sub_002C52D0_0x02c52d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDevVif0Reset(rdram, ctx, runtime);
}

void sub_002C5FA8_0x02c5fa8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadInit(rdram, ctx, runtime);
}

void sub_002C60B8_0x02c60b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadInit2(rdram, ctx, runtime);
}

void sub_002C6160_0x02c6160(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadEnd(rdram, ctx, runtime);
}

void sub_002C61E8_0x02c61e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadPortOpen(rdram, ctx, runtime);
}

void sub_002C6328_0x02c6328(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadPortClose(rdram, ctx, runtime);
}

void sub_002C63A8_0x02c63a8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadRead(rdram, ctx, runtime);
}

void sub_002C6430_0x02c6430(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadGetState(rdram, ctx, runtime);
}

void sub_002C64E0_0x02c64e0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadStateIntToStr(rdram, ctx, runtime);
}

void sub_002C6518_0x02c6518(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadSetReqState(rdram, ctx, runtime);
}

void sub_002C6588_0x02c6588(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadGetReqState(rdram, ctx, runtime);
}

void sub_002C6620_0x02c6620(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadGetFrameCount(rdram, ctx, runtime);
}

void sub_002C6680_0x02c6680(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadInfoAct(rdram, ctx, runtime);
}

void sub_002C6708_0x02c6708(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadInfoComb(rdram, ctx, runtime);
}

void sub_002C6790_0x02c6790(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadInfoMode(rdram, ctx, runtime);
}

void sub_002C6818_0x02c6818(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadSetMainMode(rdram, ctx, runtime);
}

void sub_002C68D8_0x02c68d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadSetActDirect(rdram, ctx, runtime);
}

void sub_002C6978_0x02c6978(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadSetActAlign(rdram, ctx, runtime);
}

void sub_002C6A58_0x02c6a58(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadGetButtonMask(rdram, ctx, runtime);
}

void sub_002C6AD8_0x02c6ad8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadSetButtonInfo(rdram, ctx, runtime);
}

void sub_002C6B98_0x02c6b98(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadInfoPressMode(rdram, ctx, runtime);
}

void sub_002C6C08_0x02c6c08(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadSetVrefParam(rdram, ctx, runtime);
}

void sub_002C6CE0_0x02c6ce0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadGetPortMax(rdram, ctx, runtime);
}

void sub_002C6D58_0x02c6d58(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePadGetSlotMax(rdram, ctx, runtime);
}

void sub_002C6DD0_0x02c6dd0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdCallback(rdram, ctx, runtime);
}

void sub_002C6F40_0x02c6f40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdInitEeCB(rdram, ctx, runtime);
}

void sub_002C7188_0x02c7188(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdIntToPos(rdram, ctx, runtime);
}

void sub_002C7250_0x02c7250(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdPosToInt(rdram, ctx, runtime);
}

void sub_002C72B0_0x02c72b0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdSearchFile(rdram, ctx, runtime);
}

void sub_002C76B8_0x02c76b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdNcmdDiskReady(rdram, ctx, runtime);
}

void sub_002C7750_0x02c7750(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdGetReadPos(rdram, ctx, runtime);
}

void sub_002C7780_0x02c7780(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdRead(rdram, ctx, runtime);
}

void sub_002C7950_0x02c7950(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdReadIOPm(rdram, ctx, runtime);
}

void sub_002C7A98_0x02c7a98(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdGetToc(rdram, ctx, runtime);
}

void sub_002C7D08_0x02c7d08(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdSeek(rdram, ctx, runtime);
}

void sub_002C7DF0_0x02c7df0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStandby(rdram, ctx, runtime);
}

void sub_002C7EB0_0x02c7eb0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStop(rdram, ctx, runtime);
}

void sub_002C7F78_0x02c7f78(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdPause(rdram, ctx, runtime);
}

void sub_002C8038_0x02c8038(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdSync(rdram, ctx, runtime);
}

void sub_002C80E0_0x02c80e0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdSyncS(rdram, ctx, runtime);
}

void sub_002C8290_0x02c8290(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdInit(rdram, ctx, runtime);
}

void sub_002C8488_0x02c8488(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdDiskReady(rdram, ctx, runtime);
}

void sub_002C8670_0x02c8670(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdBreak(rdram, ctx, runtime);
}

void sub_002C8708_0x02c8708(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdGetDiskType(rdram, ctx, runtime);
}

void sub_002C87A0_0x02c87a0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStatus(rdram, ctx, runtime);
}

void sub_002C8858_0x02c8858(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdGetError(rdram, ctx, runtime);
}

void sub_002C88F0_0x02c88f0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C89C8_0x02c89c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C8C90_0x02c8c90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdReadClock(rdram, ctx, runtime);
}

void sub_002C8D88_0x02c8d88(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdTrayReq(rdram, ctx, runtime);
}

void sub_002C8E90_0x02c8e90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStStart(rdram, ctx, runtime);
}

void sub_002C8EB8_0x02c8eb8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStSeek(rdram, ctx, runtime);
}

void sub_002C8EE8_0x02c8ee8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStStop(rdram, ctx, runtime);
}

void sub_002C8F18_0x02c8f18(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStRead(rdram, ctx, runtime);
}

void sub_002C9080_0x02c9080(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStStat(rdram, ctx, runtime);
}

void sub_002C90C8_0x02c90c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceCdStream(rdram, ctx, runtime);
}

void sub_002C9228_0x02c9228(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcInit(rdram, ctx, runtime);
}

void sub_002C93A0_0x02c93a0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcOpen(rdram, ctx, runtime);
}

void sub_002C9478_0x02c9478(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcMkdir(rdram, ctx, runtime);
}

void sub_002C94A8_0x02c94a8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcClose(rdram, ctx, runtime);
}

void sub_002C9528_0x02c9528(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcSeek(rdram, ctx, runtime);
}

void sub_002C95B0_0x02c95b0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::mceIntrReadFixAlign(rdram, ctx, runtime);
}

void sub_002C9640_0x02c9640(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcRead(rdram, ctx, runtime);
}

void sub_002C9710_0x02c9710(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcWrite(rdram, ctx, runtime);
}

void sub_002C9838_0x02c9838(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcSync(rdram, ctx, runtime);
}

void sub_002C9920_0x02c9920(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::mceGetInfoApdx(rdram, ctx, runtime);
}

void sub_002C9968_0x02c9968(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcGetInfo(rdram, ctx, runtime);
}

void sub_002C9A90_0x02c9a90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcGetDir(rdram, ctx, runtime);
}

void sub_002C9B70_0x02c9b70(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::mceStorePwd(rdram, ctx, runtime);
}

void sub_002C9BF8_0x02c9bf8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcChdir(rdram, ctx, runtime);
}

void sub_002C9CD8_0x02c9cd8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcFormat(rdram, ctx, runtime);
}

void sub_002C9D60_0x02c9d60(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcDelete(rdram, ctx, runtime);
}

void sub_002C9E30_0x02c9e30(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcFlush(rdram, ctx, runtime);
}

void sub_002C9EB0_0x02c9eb0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcSetFileInfo(rdram, ctx, runtime);
}

void sub_002C9FF8_0x02c9ff8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcRename(rdram, ctx, runtime);
}

void sub_002CA0E8_0x02ca0e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcUnformat(rdram, ctx, runtime);
}

void sub_002CA170_0x02ca170(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceMcGetEntSpace(rdram, ctx, runtime);
}

void sub_002CA220_0x02ca220(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0ApplyMatrix(rdram, ctx, runtime);
}

void sub_002CA250_0x02ca250(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0MulMatrix(rdram, ctx, runtime);
}

void sub_002CA2B8_0x02ca2b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0InnerProduct(rdram, ctx, runtime);
}

void sub_002CA2E0_0x02ca2e0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0Normalize(rdram, ctx, runtime);
}

void sub_002CA318_0x02ca318(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0TransposeMatrix(rdram, ctx, runtime);
}

void sub_002CA360_0x02ca360(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0InversMatrix(rdram, ctx, runtime);
}

void sub_002CA3D0_0x02ca3d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0DivVector(rdram, ctx, runtime);
}

void sub_002CA3F0_0x02ca3f0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0DivVectorXYZ(rdram, ctx, runtime);
}

void sub_002CA410_0x02ca410(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0InterVector(rdram, ctx, runtime);
}

void sub_002CA498_0x02ca498(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0TransMatrix(rdram, ctx, runtime);
}

void sub_002CA4D8_0x02ca4d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0CopyMatrix(rdram, ctx, runtime);
}

void sub_002CA540_0x02ca540(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0UnitMatrix(rdram, ctx, runtime);
}

void sub_002CA568_0x02ca568(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002CA5E0_0x02ca5e0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0RotMatrixZ(rdram, ctx, runtime);
}

void sub_002CA680_0x02ca680(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0RotMatrixX(rdram, ctx, runtime);
}

void sub_002CA720_0x02ca720(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0RotMatrixY(rdram, ctx, runtime);
}

void sub_002CA7C0_0x02ca7c0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0RotMatrix(rdram, ctx, runtime);
}

void sub_002CA810_0x02ca810(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0ClampVector(rdram, ctx, runtime);
}

void sub_002CA838_0x02ca838(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0CameraMatrix(rdram, ctx, runtime);
}

void sub_002CA8E8_0x02ca8e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0NormalLightMatrix(rdram, ctx, runtime);
}

void sub_002CA9A0_0x02ca9a0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0LightColorMatrix(rdram, ctx, runtime);
}

void sub_002CAA08_0x02caa08(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0ViewScreenMatrix(rdram, ctx, runtime);
}

void sub_002CAB10_0x02cab10(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0DropShadowMatrix(rdram, ctx, runtime);
}

void sub_002CACA0_0x02caca0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0RotTransPersN(rdram, ctx, runtime);
}

void sub_002CACF8_0x02cacf8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0RotTransPers(rdram, ctx, runtime);
}

void sub_002CAD60_0x02cad60(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0InterVectorXYZ(rdram, ctx, runtime);
}

void sub_002CADA8_0x02cada8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0ClipScreen(rdram, ctx, runtime);
}

void sub_002CADF0_0x02cadf0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0ClipScreen3(rdram, ctx, runtime);
}

void sub_002CAE50_0x02cae50(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVu0ClipAll(rdram, ctx, runtime);
}

void sub_002CAEE0_0x02caee0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceVpu0Reset(rdram, ctx, runtime);
}

void sub_002CB4C8_0x02cb4c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::atan2(rdram, ctx, runtime);
}

void sub_002CB730_0x02cb730(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::pow(rdram, ctx, runtime);
}

void sub_002CD580_0x02cd580(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ieee754_rem_pio2f_stub(rdram, ctx, runtime);
}

void sub_002CDAA8_0x02cdaa8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::__kernel_cosf(rdram, ctx, runtime);
}

void sub_002CE4E0_0x02ce4e0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::__kernel_sinf(rdram, ctx, runtime);
}

void sub_002CE618_0x02ce618(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::atan(rdram, ctx, runtime);
}

void sub_002CEA28_0x02cea28(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::fabs(rdram, ctx, runtime);
}

void sub_002CF6A0_0x02cf6a0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::divdi3_stub(rdram, ctx, runtime);
}

void sub_002D5328_0x02d5328(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::malloc_extend_top(rdram, ctx, runtime);
}

void sub_002D5590_0x02d5590(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D5D00_0x02d5d00(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::memcpy(rdram, ctx, runtime);
}

void sub_002D5DB0_0x02d5db0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::memset(rdram, ctx, runtime);
}

void sub_002D5E80_0x02d5e80(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D5ED0_0x02d5ed0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::printf(rdram, ctx, runtime);
}

void sub_002D5F40_0x02d5f40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::rand(rdram, ctx, runtime);
}

void sub_002D6430_0x02d6430(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sprintf(rdram, ctx, runtime);
}

void sub_002D64B0_0x02d64b0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::strcat(rdram, ctx, runtime);
}

void sub_002D65EC_0x02d65ec(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::strcmp(rdram, ctx, runtime);
}

void sub_002D6730_0x02d6730(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::strcpy(rdram, ctx, runtime);
}

void sub_002D6844_0x02d6844(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::strlen(rdram, ctx, runtime);
}

void sub_002D6980_0x02d6980(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::strncmp(rdram, ctx, runtime);
}

void sub_002D6B38_0x02d6b38(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::strncpy(rdram, ctx, runtime);
}

void sub_002D9AF8_0x02d9af8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::fflush(rdram, ctx, runtime);
}

void sub_002D9E60_0x02d9e60(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DA188_0x02da188(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DA988_0x02da988(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DA9C4_0x02da9c4(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::memchr(rdram, ctx, runtime);
}

void sub_002DAAA4_0x02daaa4(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::memmove(rdram, ctx, runtime);
}

void sub_002DBD88_0x02dbd88(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DC8C0_0x02dc8c0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::write(rdram, ctx, runtime);
}

void sub_002DC940_0x02dc940(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::read(rdram, ctx, runtime);
}

void sub_002DCD50_0x02dcd50(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_syscalls::SetAlarm(rdram, ctx, runtime);
}

void sub_002DCF90_0x02dcf90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceTtyHandler(rdram, ctx, runtime);
}

void sub_002DD110_0x02dd110(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceTtyWrite(rdram, ctx, runtime);
}

void sub_002DD260_0x02dd260(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceTtyRead(rdram, ctx, runtime);
}

void sub_002DD338_0x02dd338(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceTtyInit(rdram, ctx, runtime);
}

void sub_002DD810_0x02dd810(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DDDB0_0x02dddb0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::scePrintf(rdram, ctx, runtime);
}

void sub_002DDE98_0x02dde98(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifInitCmd(rdram, ctx, runtime);
}

void sub_002DE110_0x02de110(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifExitCmd(rdram, ctx, runtime);
}

void sub_002DE168_0x02de168(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifAddCmdHandler(rdram, ctx, runtime);
}

void sub_002DE198_0x02de198(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifRemoveCmdHandler(rdram, ctx, runtime);
}

void sub_002DE1C0_0x02de1c0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DE300_0x02de300(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifSendCmd(rdram, ctx, runtime);
}

void sub_002DE380_0x02de380(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DE498_0x02de498(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifWriteBackDCache(rdram, ctx, runtime);
}

void sub_002DE548_0x02de548(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifInitRpc(rdram, ctx, runtime);
}

void sub_002DE700_0x02de700(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DE7C8_0x02de7c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DE7F8_0x02de7f8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DE948_0x02de948(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifGetOtherData(rdram, ctx, runtime);
}

void sub_002DEB80_0x02deb80(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifBindRpc(rdram, ctx, runtime);
}

void sub_002DED30_0x02ded30(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_syscalls::sceSifCallRpc(rdram, ctx, runtime);
}

void sub_002DEEE8_0x02deee8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifCheckStatRpc(rdram, ctx, runtime);
}

void sub_002DEF28_0x02def28(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifSetRpcQueue(rdram, ctx, runtime);
}

void sub_002DEFA0_0x02defa0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifRegisterRpc(rdram, ctx, runtime);
}

void sub_002DF030_0x02df030(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifRemoveRpc(rdram, ctx, runtime);
}

void sub_002DF0B0_0x02df0b0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifRemoveRpcQueue(rdram, ctx, runtime);
}

void sub_002DF138_0x02df138(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifGetNextRequest(rdram, ctx, runtime);
}

void sub_002DF188_0x02df188(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifExecRequest(rdram, ctx, runtime);
}

void sub_002DF368_0x02df368(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifRpcLoop(rdram, ctx, runtime);
}

void sub_002DF440_0x02df440(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceFsInit(rdram, ctx, runtime);
}

void sub_002DF538_0x02df538(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceOpen(rdram, ctx, runtime);
}

void sub_002DF690_0x02df690(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceClose(rdram, ctx, runtime);
}

void sub_002DF748_0x02df748(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceLseek(rdram, ctx, runtime);
}

void sub_002DF8B8_0x02df8b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceRead(rdram, ctx, runtime);
}

void sub_002DF9E8_0x02df9e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceWrite(rdram, ctx, runtime);
}

void sub_002DFB68_0x02dfb68(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceIoctl(rdram, ctx, runtime);
}

void sub_002DFC00_0x02dfc00(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifInitIopHeap(rdram, ctx, runtime);
}

void sub_002DFC90_0x02dfc90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifAllocIopHeap(rdram, ctx, runtime);
}

void sub_002DFD78_0x02dfd78(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifLoadIopHeap(rdram, ctx, runtime);
}

void sub_002DFF18_0x02dff18(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002E0018_0x02e0018(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002E0128_0x02e0128(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifLoadElf(rdram, ctx, runtime);
}

void sub_002E0150_0x02e0150(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifGetIopAddr(rdram, ctx, runtime);
}

void sub_002E0240_0x02e0240(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifSetIopAddr(rdram, ctx, runtime);
}

void sub_002E0320_0x02e0320(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifResetIop(rdram, ctx, runtime);
}

void sub_002E0450_0x02e0450(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifIsAliveIop(rdram, ctx, runtime);
}

void sub_002E0478_0x02e0478(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifSyncIop(rdram, ctx, runtime);
}

void sub_002E04C0_0x02e04c0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceSifRebootIop(rdram, ctx, runtime);
}

void sub_002E05B8_0x02e05b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2Open(rdram, ctx, runtime);
}

void sub_002E05E8_0x02e05e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2Close(rdram, ctx, runtime);
}

void sub_002E0610_0x02e0610(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2ReqSend(rdram, ctx, runtime);
}

void sub_002E0640_0x02e0640(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2Poll(rdram, ctx, runtime);
}

void sub_002E0668_0x02e0668(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2ExRecv(rdram, ctx, runtime);
}

void sub_002E06A0_0x02e06a0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2ExSend(rdram, ctx, runtime);
}

void sub_002E06D8_0x02e06d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2ExReqSend(rdram, ctx, runtime);
}

void sub_002E0708_0x02e0708(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2ExLock(rdram, ctx, runtime);
}

void sub_002E0730_0x02e0730(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::sceDeci2ExUnLock(rdram, ctx, runtime);
}

void sub_0029FE38_0x029fe38(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C46E0_0x02c46e0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu0Pause_stub(rdram, ctx, runtime);
}

void sub_002C4790_0x02c4790(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu0PutDBit_stub(rdram, ctx, runtime);
}

void sub_002C47C0_0x02c47c0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu0PutTBit_stub(rdram, ctx, runtime);
}

void sub_002C4810_0x02c4810(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu0Sync_stub(rdram, ctx, runtime);
}

void sub_002C4870_0x02c4870(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu0GetCnd_stub(rdram, ctx, runtime);
}

void sub_002C4950_0x02c4950(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu0PutCnd_stub(rdram, ctx, runtime);
}

void sub_002C4AC0_0x02c4ac0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::vuCheckBusy_stub(rdram, ctx, runtime);
}

void sub_002C4AF0_0x02c4af0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::vu0MemWriteQ_stub(rdram, ctx, runtime);
}

void sub_002C4B30_0x02c4b30(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::vu0MemReadQ_stub(rdram, ctx, runtime);
}

void sub_002C4B90_0x02c4b90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu1Pause_stub(rdram, ctx, runtime);
}

void sub_002C4C40_0x02c4c40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu1PutDBit_stub(rdram, ctx, runtime);
}

void sub_002C4C70_0x02c4c70(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu1PutTBit_stub(rdram, ctx, runtime);
}

void sub_002C4CC0_0x02c4cc0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu1Sync_stub(rdram, ctx, runtime);
}

void sub_002C4D18_0x02c4d18(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu1GetTpc_stub(rdram, ctx, runtime);
}

void sub_002C4D40_0x02c4d40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu1GetCnd_stub(rdram, ctx, runtime);
}

void sub_002C4ED0_0x02c4ed0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVu1PutCnd_stub(rdram, ctx, runtime);
}

void sub_002C5048_0x02c5048(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devGifContinue_stub(rdram, ctx, runtime);
}

void sub_002C5080_0x02c5080(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devGifPutImtMode_stub(rdram, ctx, runtime);
}

void sub_002C5100_0x02c5100(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devGifPutP3msk_stub(rdram, ctx, runtime);
}

void sub_002C5188_0x02c5188(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devGifSync_stub(rdram, ctx, runtime);
}

void sub_002C51B8_0x02c51b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devGifGetCnd_stub(rdram, ctx, runtime);
}

void sub_002C5270_0x02c5270(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devGifPutFifo_stub(rdram, ctx, runtime);
}

void sub_002C52F8_0x02c52f8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif0Pause_stub(rdram, ctx, runtime);
}

void sub_002C5360_0x02c5360(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif0Continue_stub(rdram, ctx, runtime);
}

void sub_002C53A0_0x02c53a0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif0PutErr_stub(rdram, ctx, runtime);
}

void sub_002C53D0_0x02c53d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif0Sync_stub(rdram, ctx, runtime);
}

void sub_002C5420_0x02c5420(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif0GetCnd_stub(rdram, ctx, runtime);
}

void sub_002C55A0_0x02c55a0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif0PutFifo_stub(rdram, ctx, runtime);
}

void sub_002C5600_0x02c5600(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif1Reset_stub(rdram, ctx, runtime);
}

void sub_002C5628_0x02c5628(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif1Pause_stub(rdram, ctx, runtime);
}

void sub_002C5690_0x02c5690(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif1Continue_stub(rdram, ctx, runtime);
}

void sub_002C56D0_0x02c56d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif1PutErr_stub(rdram, ctx, runtime);
}

void sub_002C5700_0x02c5700(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif1Sync_stub(rdram, ctx, runtime);
}

void sub_002C5750_0x02c5750(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif1GetCnd_stub(rdram, ctx, runtime);
}

void sub_002C5928_0x02c5928(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif1PutFifo_stub(rdram, ctx, runtime);
}

void sub_002C5988_0x02c5988(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::devVif1GetFifo_stub(rdram, ctx, runtime);
}

void sub_002C59E8_0x02c59e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C5AC0_0x02c5ac0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C5DB8_0x02c5db8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C5E20_0x02c5e20(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C6E10_0x02c6e10(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C6E90_0x02c6e90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C7018_0x02c7018(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C70B0_0x02c70b0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C7138_0x02c7138(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C7570_0x02c7570(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C8148_0x02c8148(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C8AB0_0x02c8ab0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002C8B98_0x02c8b98(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002CAF40_0x02caf40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::atanf_stub(rdram, ctx, runtime);
}

void sub_002CB1E8_0x02cb1e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::cosf_stub(rdram, ctx, runtime);
}

void sub_002CB2F0_0x02cb2f0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::floorf_stub(rdram, ctx, runtime);
}

void sub_002CB3D8_0x02cb3d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::sinf_stub(rdram, ctx, runtime);
}

void sub_002CBB60_0x02cbb60(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::atan2f_stub(rdram, ctx, runtime);
}

void sub_002CBC88_0x02cbc88(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::sqrtf_stub(rdram, ctx, runtime);
}

void sub_002CBDA0_0x02cbda0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ieee754_atan2_stub(rdram, ctx, runtime);
}

void sub_002CC0D8_0x02cc0d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ieee754_log10_stub(rdram, ctx, runtime);
}

void sub_002CC260_0x02cc260(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ieee754_pow_stub(rdram, ctx, runtime);
}

void sub_002CCF98_0x02ccf98(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ieee754_sqrt_stub(rdram, ctx, runtime);
}

void sub_002CD298_0x02cd298(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ieee754_atan2f_stub(rdram, ctx, runtime);
}

void sub_002CD978_0x02cd978(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ieee754_sqrtf_stub(rdram, ctx, runtime);
}

void sub_002CDC30_0x02cdc30(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::kernel_rem_pio2f_stub(rdram, ctx, runtime);
}

void sub_002CEAB8_0x02ceab8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::matherr_stub(rdram, ctx, runtime);
}

void sub_002CEAE0_0x02ceae0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::rint_stub(rdram, ctx, runtime);
}

void sub_002CF020_0x02cf020(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ieee754_log_stub(rdram, ctx, runtime);
}

void sub_002CFD80_0x02cfd80(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002CFDA8_0x02cfda8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::TODO_NAMED("__throw_type_match", rdram, ctx, runtime);
}

void sub_002CFDE0_0x02cfde0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002CFE58_0x02cfe58(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002CFE80_0x02cfe80(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002CFEA8_0x02cfea8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002CFF08_0x02cff08(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002CFF30_0x02cff30(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D00A8_0x02d00a8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D01B0_0x02d01b0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D0208_0x02d0208(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D02E0_0x02d02e0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D0428_0x02d0428(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D04B8_0x02d04b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D0538_0x02d0538(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D05D0_0x02d05d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D08F0_0x02d08f0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D0AB8_0x02d0ab8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D0C90_0x02d0c90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::floatdisf_stub(rdram, ctx, runtime);
}

void sub_002D0D70_0x02d0d70(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::muldi3_stub(rdram, ctx, runtime);
}

void sub_002D0DD0_0x02d0dd0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::TODO_NAMED("__pack_d", rdram, ctx, runtime);
}

void sub_002D0F00_0x02d0f00(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::TODO_NAMED("__unpack_d", rdram, ctx, runtime);
}

void sub_002D0FA0_0x02d0fa0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpadd_parts_stub(rdram, ctx, runtime);
}

void sub_002D11D8_0x02d11d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::dpadd_stub(rdram, ctx, runtime);
}

void sub_002D1230_0x02d1230(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::dpsub_stub(rdram, ctx, runtime);
}

void sub_002D1298_0x02d1298(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::dpmul_stub(rdram, ctx, runtime);
}

void sub_002D1550_0x02d1550(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::dpdiv_stub(rdram, ctx, runtime);
}

void sub_002D16B0_0x02d16b0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpcmp_parts_stub(rdram, ctx, runtime);
}

void sub_002D17C8_0x02d17c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::dpcmp_stub(rdram, ctx, runtime);
}

void sub_002D1818_0x02d1818(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::litodp_stub(rdram, ctx, runtime);
}

void sub_002D18D0_0x02d18d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::dptoli_stub(rdram, ctx, runtime);
}

void sub_002D1968_0x02d1968(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::dptoul_stub(rdram, ctx, runtime);
}

void sub_002D1A08_0x02d1a08(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::negdf2_stub(rdram, ctx, runtime);
}

void sub_002D1A40_0x02d1a40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::TODO_NAMED("__make_dp", rdram, ctx, runtime);
}

void sub_002D1A70_0x02d1a70(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::dptofp_stub(rdram, ctx, runtime);
}

void sub_002D1B28_0x02d1b28(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D1B70_0x02d1b70(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D1BA8_0x02d1ba8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D1BF0_0x02d1bf0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D1C60_0x02d1c60(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D1DB0_0x02d1db0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D20A0_0x02d20a0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D2238_0x02d2238(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::TODO_NAMED("__pack_f", rdram, ctx, runtime);
}

void sub_002D2348_0x02d2348(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::TODO_NAMED("__unpack_f", rdram, ctx, runtime);
}

void sub_002D23D8_0x02d23d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpadd_parts_stub(rdram, ctx, runtime);
}

void sub_002D2610_0x02d2610(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpadd_stub(rdram, ctx, runtime);
}

void sub_002D2668_0x02d2668(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpsub_stub(rdram, ctx, runtime);
}

void sub_002D26D0_0x02d26d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpmul_stub(rdram, ctx, runtime);
}

void sub_002D28C8_0x02d28c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpdiv_stub(rdram, ctx, runtime);
}

void sub_002D2A20_0x02d2a20(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpcmp_parts_stub(rdram, ctx, runtime);
}

void sub_002D2B38_0x02d2b38(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fpcmp_stub(rdram, ctx, runtime);
}

void sub_002D2B88_0x02d2b88(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::sitofp_stub(rdram, ctx, runtime);
}

void sub_002D2C40_0x02d2c40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fptosi_stub(rdram, ctx, runtime);
}

void sub_002D2CD0_0x02d2cd0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fptoui_stub(rdram, ctx, runtime);
}

void sub_002D2D68_0x02d2d68(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::negsf2_stub(rdram, ctx, runtime);
}

void sub_002D2DA0_0x02d2da0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    ps2_stubs::TODO_NAMED("__make_fp", rdram, ctx, runtime);
}

void sub_002D2DD0_0x02d2dd0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fptodp_stub(rdram, ctx, runtime);
}

void sub_002D2E10_0x02d2e10(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D2E58_0x02d2e58(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D2EA8_0x02d2ea8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D2FA8_0x02d2fa8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3200_0x02d3200(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3240_0x02d3240(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D32C8_0x02d32c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D33F0_0x02d33f0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D34D8_0x02d34d8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D35F0_0x02d35f0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3978_0x02d3978(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D39D0_0x02d39d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3A28_0x02d3a28(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3AC8_0x02d3ac8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3C90_0x02d3c90(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3E78_0x02d3e78(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3EA8_0x02d3ea8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3EE8_0x02d3ee8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3F50_0x02d3f50(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D3F80_0x02d3f80(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D4540_0x02d4540(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D4A30_0x02d4a30(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D4AA0_0x02d4aa0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D4B48_0x02d4b48(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D5F70_0x02d5f70(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D5FD0_0x02d5fd0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D6040_0x02d6040(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D60D0_0x02d60d0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D61C8_0x02d61c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D63B8_0x02d63b8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D6CF8_0x02d6cf8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D6D40_0x02d6d40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D6E28_0x02d6e28(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D83C8_0x02d83c8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D8570_0x02d8570(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::exponent_stub(rdram, ctx, runtime);
}

void sub_002D8650_0x02d8650(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D8760_0x02d8760(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D8980_0x02d8980(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D9C08_0x02d9c08(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D9C60_0x02d9c60(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D9CD0_0x02d9cd0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002D9DD0_0x02d9dd0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DA2F8_0x02da2f8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DA6C0_0x02da6c0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DA758_0x02da758(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DA840_0x02da840(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DABA8_0x02daba8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DAC50_0x02dac50(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DAC80_0x02dac80(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DAD88_0x02dad88(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DAEC0_0x02daec0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DAF48_0x02daf48(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB008_0x02db008(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB040_0x02db040(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB248_0x02db248(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB348_0x02db348(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB4B0_0x02db4b0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB518_0x02db518(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB6A8_0x02db6a8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB740_0x02db740(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DB8C0_0x02db8c0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DBA40_0x02dba40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DBB00_0x02dbb00(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DBBB8_0x02dbbb8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DBC20_0x02dbc20(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DBCA0_0x02dbca0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DBE48_0x02dbe48(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DC830_0x02dc830(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DC868_0x02dc868(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DC9F8_0x02dc9f8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DCAC8_0x02dcac8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DCB40_0x02dcb40(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DCF10_0x02dcf10(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DCF50_0x02dcf50(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DD3F8_0x02dd3f8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DD430_0x02dd430(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DD4E0_0x02dd4e0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DD518_0x02dd518(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ftoi_stub(rdram, ctx, runtime);
}

void sub_002DD5A8_0x02dd5a8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::itof_stub(rdram, ctx, runtime);
}

void sub_002DD670_0x02dd670(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DDD68_0x02ddd68(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DE340_0x02de340(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DE838_0x02de838(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DE8E8_0x02de8e8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DEA80_0x02dea80(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DEAD0_0x02dead0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DECA0_0x02deca0(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DF3A8_0x02df3a8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DF418_0x02df418(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DF828_0x02df828(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002DFE58_0x02dfe58(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002E0758_0x02e0758(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::ret0(rdram, ctx, runtime);
}

void sub_002E0780_0x02e0780(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::fixunsdfdi_stub(rdram, ctx, runtime);
}

void sub_002E0870_0x02e0870(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::floatdidf_stub(rdram, ctx, runtime);
}

void sub_002E0908_0x02e0908(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::moddi3_stub(rdram, ctx, runtime);
}

void sub_002E0F38_0x02e0f38(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::udivdi3_stub(rdram, ctx, runtime);
}

void sub_002E14F8_0x02e14f8(uint8_t* rdram, R5900Context* ctx, PS2Runtime* runtime) {
    rrv_hle::umoddi3_stub(rdram, ctx, runtime);
}
