# ADR-0006 fixed-root package configuration.  Only this module configures the
# producer command; consumers are typed readers and never parse a package JSON.
get_filename_component(_RRV_RP_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." REALPATH)
set(_RRV_RP_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(_rrv_rp_require_native)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" AND
       CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" AND CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "x86_64")
        # Gate 5: native Linux x86-64 (Steam Deck); same fixed-root contract.
    elseif(NOT APPLE OR NOT CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "arm64" OR NOT CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64" OR (CMAKE_OSX_ARCHITECTURES AND NOT CMAKE_OSX_ARCHITECTURES STREQUAL "arm64"))
        message(FATAL_ERROR "ADR-0006 resource package requires native macOS arm64 or Linux x86-64")
    endif()
    if(NOT CMAKE_GENERATOR STREQUAL "Ninja" OR CMAKE_CONFIGURATION_TYPES OR NOT CMAKE_BUILD_TYPE STREQUAL "Release")
        message(FATAL_ERROR "ADR-0006 resource package requires single-config Ninja Release")
    endif()
    find_package(Python3 REQUIRED COMPONENTS Interpreter)
    set(Python3_EXECUTABLE "${Python3_EXECUTABLE}" PARENT_SCOPE)
endfunction()

function(rrv_select_gs_resource_package)
    cmake_parse_arguments(RRP "" "PACKAGE;MANIFEST" "" ${ARGN})
    if(NOT RRP_PACKAGE OR NOT RRP_MANIFEST OR RRP_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "rrv_select_gs_resource_package requires PACKAGE and MANIFEST")
    endif()
    _rrv_rp_require_native()
    get_filename_component(_manifest "${RRP_MANIFEST}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
    if(NOT EXISTS "${_manifest}")
        message(FATAL_ERROR "resource package input is absent: ${_manifest}")
    endif()
    set(_control "${CMAKE_BINARY_DIR}/CMakeFiles/rrv-resource-package")
    set(_spec "${_control}/spec.json")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "PYTHONDONTWRITEBYTECODE=1" "${Python3_EXECUTABLE}" -B "${_RRV_RP_SOURCE_ROOT}/scripts/resource_package.py" inspect
        --input "${_manifest}" --build-root "${CMAKE_BINARY_DIR}" --spec "${_spec}"
        RESULT_VARIABLE _inspect_status OUTPUT_VARIABLE _requested_composition ERROR_VARIABLE _inspect_stderr)
    if(NOT _inspect_status EQUAL 0)
        message(FATAL_ERROR "resource package inspection failed (${_inspect_status}) at ${_RRV_RP_SOURCE_ROOT}: ${_inspect_stderr}")
    endif()
    string(STRIP "${_requested_composition}" _requested_composition)
    get_property(_old_composition GLOBAL PROPERTY RRV_RESOURCE_PACKAGE_COMPOSITION)
    if(_old_composition AND NOT _old_composition STREQUAL _requested_composition)
        message(FATAL_ERROR "one build may configure only one resource composition")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "PYTHONDONTWRITEBYTECODE=1" "${Python3_EXECUTABLE}" -B "${_RRV_RP_SOURCE_ROOT}/scripts/resource_package.py" configure
        --input "${_manifest}" --build-root "${CMAKE_BINARY_DIR}" --spec "${_spec}"
        RESULT_VARIABLE _configure_status OUTPUT_VARIABLE _configure_stdout ERROR_VARIABLE _configure_stderr)
    if(NOT _configure_status EQUAL 0)
        message(FATAL_ERROR "resource package configuration failed: ${_configure_stdout}${_configure_stderr}")
    endif()
    file(SHA256 "${_spec}" _spec_sha256)
    get_property(_old_spec GLOBAL PROPERTY RRV_RESOURCE_PACKAGE_SPEC_SHA256)
    if(_old_spec AND NOT _old_spec STREQUAL _spec_sha256)
        message(FATAL_ERROR "one build may configure only one resource composition")
    endif()
    set_property(GLOBAL PROPERTY RRV_RESOURCE_PACKAGE_SPEC_SHA256 "${_spec_sha256}")
    set_property(GLOBAL PROPERTY RRV_RESOURCE_PACKAGE_COMPOSITION "${_requested_composition}")
    set_property(GLOBAL PROPERTY RRV_RESOURCE_PACKAGE_NAME "${RRP_PACKAGE}")

    file(READ "${_spec}" _spec_json)
    string(JSON _composition GET "${_spec_json}" composition)
    string(JSON _version GET "${_spec_json}" version)
    string(JSON _bridge GET "${_spec_json}" bridge)
    string(JSON _count LENGTH "${_spec_json}" inventory)
    set(RRV_RESOURCE_PACKAGE_ENTRIES "")
    if(_count GREATER 0)
        math(EXPR _last "${_count} - 1")
        foreach(_index RANGE ${_last})
            string(JSON _path GET "${_spec_json}" inventory ${_index} path)
            string(JSON _type GET "${_spec_json}" inventory ${_index} type)
            if(_type STREQUAL "file")
                string(JSON _size GET "${_spec_json}" inventory ${_index} size)
                string(JSON _sha GET "${_spec_json}" inventory ${_index} sha256)
                set(_kind "file")
            elseif(_type STREQUAL "directory")
                set(_size 0)
                set(_sha "")
                set(_kind "directory")
            else()
                message(FATAL_ERROR "resource package spec contains an invalid typed entry")
            endif()
            string(APPEND RRV_RESOURCE_PACKAGE_ENTRIES "    {\"${_path}\", rrv::resource_package::EntryType::${_kind}, ${_size}ULL, \"${_sha}\"},\n")
        endforeach()
    endif()
    set(RRV_RESOURCE_PACKAGE_VERSION "${_version}")
    set(RRV_RESOURCE_PACKAGE_COMPOSITION "${_composition}")
    set(RRV_RESOURCE_PACKAGE_BRIDGE "${_bridge}")
    set(_binding "${_control}/binding.cpp")
    configure_file("${_RRV_RP_MODULE_DIR}/rrv_resource_package_binding.cpp.in" "${_binding}" @ONLY)
    set(_entrypoint "${_control}/ensure.py")
    # `repr` is generated by the configured interpreter, not hand-escaped CMake
    # text, so source roots such as O'Brien and non-ASCII names remain a single
    # Python string literal in the fixed build-local entrypoint.
    execute_process(COMMAND "${Python3_EXECUTABLE}" -c "import sys; print(repr(sys.argv[1]))" "${_RRV_RP_SOURCE_ROOT}/scripts"
        RESULT_VARIABLE _quote_status OUTPUT_VARIABLE _scripts_literal ERROR_VARIABLE _quote_stderr)
    if(NOT _quote_status EQUAL 0)
        message(FATAL_ERROR "resource package entrypoint quoting failed: ${_quote_stderr}")
    endif()
    string(STRIP "${_scripts_literal}" _scripts_literal)
    file(WRITE "${_entrypoint}" "import pathlib, sys\nsys.path.insert(0, ${_scripts_literal})\nimport resource_package\nresource_package.ensure_configured(pathlib.Path(__file__).resolve().parents[2], '${_spec_sha256}')\n")

    if(NOT TARGET rrv-resource-package-reader)
        add_library(rrv-resource-package-reader STATIC "${_RRV_RP_SOURCE_ROOT}/src/host/rrv_resource_package.cpp")
        target_include_directories(rrv-resource-package-reader PUBLIC "${_RRV_RP_SOURCE_ROOT}/src/host")
        target_compile_features(rrv-resource-package-reader PUBLIC cxx_std_17)
        add_library(rrv-resource-package-binding STATIC "${_binding}")
        target_include_directories(rrv-resource-package-binding PUBLIC "${_RRV_RP_SOURCE_ROOT}/src/host")
        target_link_libraries(rrv-resource-package-binding PUBLIC rrv-resource-package-reader)
        add_custom_target(rrv-resource-package-producer
            COMMAND "${CMAKE_COMMAND}" -E env "PYTHONDONTWRITEBYTECODE=1" "${Python3_EXECUTABLE}" -B "${_entrypoint}"
            DEPENDS "${_spec}" "${_RRV_RP_SOURCE_ROOT}/scripts/resource_package.py" "${_RRV_RP_SOURCE_ROOT}/scripts/resource_package_fs.py"
            VERBATIM)
    endif()
endfunction()

function(rrv_use_gs_resource_package)
    cmake_parse_arguments(RRP "" "TARGET;PACKAGE" "" ${ARGN})
    if(NOT RRP_TARGET OR NOT RRP_PACKAGE OR RRP_UNPARSED_ARGUMENTS OR NOT TARGET "${RRP_TARGET}")
        message(FATAL_ERROR "rrv_use_gs_resource_package requires an existing TARGET and selected PACKAGE")
    endif()
    get_property(_selected GLOBAL PROPERTY RRV_RESOURCE_PACKAGE_NAME)
    if(NOT _selected OR NOT _selected STREQUAL RRP_PACKAGE)
        message(FATAL_ERROR "resource consumer must use the one selected package")
    endif()
    get_property(_registered TARGET "${RRP_TARGET}" PROPERTY RRV_RESOURCE_PACKAGE_BOUND)
    if(_registered)
        message(FATAL_ERROR "resource consumer is already bound")
    endif()
    set_property(TARGET "${RRP_TARGET}" PROPERTY RRV_RESOURCE_PACKAGE_BOUND TRUE)
    set_target_properties("${RRP_TARGET}" PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
    target_link_libraries("${RRP_TARGET}" PRIVATE rrv-resource-package-binding)
    add_dependencies("${RRP_TARGET}" rrv-resource-package-producer)
endfunction()
